controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

events_fetch:
    path: /events
    controller: App\Controller\FlightsController::getFlights
    methods: GET

